version: '3'


services:

  database:
    container_name: database-container
    image: mysql:latest
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_LOWER_CASE_TABLE_NAMES: ${MYSQL_LOWER_CASE_TABLE_NAMES}
    volumes:
      - ./volume-fr-administration-database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:3.12-management
    restart: always
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT_1}:${RABBITMQ_PORT_1}"
      - "${RABBITMQ_PORT_2}:${RABBITMQ_PORT_2}"
    networks:
      - app-network

  backend:
    container_name: api-container
    env_file:
      - .env
    build:
      context: ./fr-administration-api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: always
    command: sh -c "npm run build && node dist/main.js"
    depends_on:
      - database
      - rabbitmq
    volumes:
      - ./fr-administration-api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
      
  nginx:
    container_name: http-server-container
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: fr-application-http-server/Dockerfile
    depends_on:
      - backend
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./fr-application-http-server/nginx.conf:/etc/nginx/nginx.conf
      - ./fr-application-http-server/html/index.html:/var/www/html/index.html
    networks:
      - app-network

  quarkus:
    container_name: quarkus-container
    restart: always
    env_file:
      - .env
    build:
      context: ./fr-administration-quarkus
      dockerfile: src/main/docker/Dockerfile.multistage
    ports:
      - "${QUARKUS_PORT}:${QUARKUS_PORT}"
    depends_on:
      - database
      - rabbitmq
    volumes:
      - ./fr-administration-quarkus:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  maildev:
    container_name: maildev-container
    image: maildev/maildev:latest
    env_file:
      - .env
    restart: always
    ports:
      - "${MAILDEV_PORT_1}:${MAILDEV_PORT_1}"
      - "${MAILDEV_PORT_2}:${MAILDEV_PORT_2}"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    env_file:
      - .env
    restart: always
    depends_on:
      - backend
      - rabbitmq
      - nginx
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    env_file:
      - .env
    restart: always
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    networks:
      - app-network


volumes:
  volume-fr-administration-database:


networks:
  app-network:
    driver: bridge