global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:80']

  - job_name: 'api'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['localhost:15672']

